### ISSUE TITLE
Get-ChromeDump

### ISSUE THREAD

**Issue by s1im3r00** [SecureThisShit/Creds#3]
Get-ChromeDump -OutFile 11.txt
You cannot call a method on a null-valued expression.
At C:\Users\Administrator\Downloads\Creds-master\Creds-master\PowershellScripts\Get-ChromeDump.ps1:410 char:12
+         if($Item.Contains('Passwords') -or $Item.Contains('History')) ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

New-Object : Cannot find type [System.Data.SQLite.SQLiteConnection]: verify that the assembly containing this type is
loaded.
At C:\Users\Administrator\Downloads\Creds-master\Creds-master\PowershellScripts\Get-ChromeDump.ps1:447 char:19
+ ... onnection = New-Object System.Data.SQLite.SQLiteConnection($connStrin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Users\Administrator\Downloads\Creds-master\Creds-master\PowershellScripts\Get-ChromeDump.ps1:449 char:5
+     $Open = $connection.OpenAndReturn()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

New-Object : Cannot find type [System.Data.SQLite.SQLiteDataAdapter]: verify that the assembly containing this type is
loaded.
At C:\Users\Administrator\Downloads\Creds-master\Creds-master\PowershellScripts\Get-ChromeDump.ps1:457 char:20
+ ... taAdapter = New-Object System.Data.SQLite.SQLiteDataAdapter($query,$O ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Users\Administrator\Downloads\Creds-master\Creds-master\PowershellScripts\Get-ChromeDump.ps1:459 char:5
+     [void]$dataAdapter.fill($DataSet)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by S3cur3Th1sSh1t** [comment]
The error message tells you what's wrong here. Use `Install-SqlLiteAssembly` before execution.

Like WinPwn does https://github.com/S3cur3Th1sSh1t/WinPwn/blob/master/WinPwn.ps1: 

![image](https://user-images.githubusercontent.com/27858067/113423992-b9398500-93cf-11eb-8a20-5339445fe4a7.png)
